checks:
  addAllBuiltIn: true
  exclude:
    - no-read-only-root-fs
    - run-as-non-root
    - unset-cpu-requirements
    - unset-memory-requirements
    - exposed-services
    - default-service-account
    - dnsconfig-options
    - no-liveness-probe
    - no-readiness-probe
    - no-rolling-update-strategy
    - non-isolated-pod
    - privileged-ports
    - read-secret-from-env-var
    - required-annotation-email
    - required-label-owner
    - minimum-three-replicas
    - no-node-affinity
    - no-anti-affinity