apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxTest
  namespace: gitopsTest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxTest
  template:
    metadata:
      labels:
        app: nginxTest
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxTest
  namespace: gitopsTest
spec:
  selector:
    app: nginxTest
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitopsTest