# Comment
apiVersion: v1
kind: Namespace
metadata:
  name: todo-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dev
  namespace: todo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-dev
  template:
    metadata:
      labels:
        app: todo-app-dev
    spec:
      containers:
      - name: php-apache
        image: php:8.1-apache
        ports:
        - containerPort: 80
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key
        volumeMounts:
        - name: html-config
          mountPath: /var/www/html
      volumes:
      - name: html-config
        configMap:
          name: weather-html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-html-config
  namespace: todo-dev
data:
  index.php: |
    <?php
    $apiKey = $_ENV['WEATHER_API_KEY'] ?? '';
    $apiUrl = "https://api.openweathermap.org/data/2.5/weather?q=Krems,AT&appid={$apiKey}&units=metric";
    
    $response = @file_get_contents($apiUrl);
    $weather = $response ? json_decode($response, true) : null;
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Weather Krems</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                text-align: center; 
                margin: 40px; 
                background: #f0f0f0; 
            }
            .temp { 
                font-size: 72px; 
                font-weight: bold; 
                color: #2c3e50; 
                margin: 20px 0; 
            }
            .location { 
                font-size: 24px; 
                color: #7f8c8d; 
                margin: 10px 0; 
            }
            .secret-info { 
                font-size: 14px; 
                color: #95a5a6; 
                margin-top: 30px; 
            }
        </style>
    </head>
    <body>
        <div class="location">Krems, Austria</div>
        
        <?php if ($weather && isset($weather['main']['temp'])): ?>
            <div class="temp"><?php echo round($weather['main']['temp']); ?>°C</div>
        <?php else: ?>
            <div class="temp">--°C</div>
        <?php endif; ?>
        
        <div class="secret-info">
            API Key: <?php echo $apiKey ? 'Loaded from Kubernetes Secret' : 'Not Found'; ?>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-dev
  namespace: todo-dev
spec:
  selector:
    app: todo-app-dev
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-dev-external
  namespace: todo-dev
spec:
  selector:
    app: todo-app-dev
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30091
  type: NodePort
